# Generated by Django 3.2.15 on 2024-02-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('titulo_style', models.CharField(blank=True, max_length=500)),
                ('data_colors', models.CharField(blank=True, max_length=900)),
                ('ticklabel_color', models.CharField(default=True, max_length=10)),
                ('ticklabel_size', models.IntegerField()),
                ('showticklabels', models.BooleanField(default=True)),
                ('create_tipo_indicador', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_tipo_indicador', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
