# Generated by Django 3.2.15 on 2024-02-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletaColores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_paleta', models.CharField(blank=True, max_length=100)),
                ('colors_list', models.CharField(blank=True, max_length=1000)),
                ('create_tipo_indicador', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_tipo_indicador', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='configdashboard',
            name='data_colors',
        ),
        migrations.RemoveField(
            model_name='configdashboard',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='configdashboard',
            name='titulo_style',
        ),
        migrations.AddField(
            model_name='configdashboard',
            name='paper_bgcolor',
            field=models.CharField(blank=True, default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='configdashboard',
            name='plot_bgcolor',
            field=models.CharField(blank=True, default='white', max_length=30),
        ),
        migrations.AlterField(
            model_name='configdashboard',
            name='ticklabel_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AlterField(
            model_name='configdashboard',
            name='ticklabel_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='configdashboard',
            name='paleta_colores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.paletacolores'),
        ),
    ]
