# Generated by Django 3.2.15 on 2024-02-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_auto_20240205_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdashboard',
            name='name_config',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
