# Generated by Django 3.2.15 on 2024-02-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_configdashboard_name_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_dashboard', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('create_tipo_dashboard', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_tipo_dashboard', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tipo_grafico', models.CharField(blank=True, max_length=200)),
                ('create_tipo_grafico', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_tipo_grafico', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='configdashboard',
            old_name='create_tipo_indicador',
            new_name='create_config_dashboard',
        ),
        migrations.RenameField(
            model_name='configdashboard',
            old_name='modified_tipo_indicador',
            new_name='modified_config_dashboard',
        ),
        migrations.RenameField(
            model_name='paletacolores',
            old_name='create_tipo_indicador',
            new_name='create_paleta_colors',
        ),
        migrations.RenameField(
            model_name='paletacolores',
            old_name='modified_tipo_indicador',
            new_name='modified_paleta_colors',
        ),
        migrations.AlterField(
            model_name='configdashboard',
            name='paper_bgcolor',
            field=models.CharField(blank=True, default='#ffffff', max_length=30),
        ),
        migrations.AlterField(
            model_name='configdashboard',
            name='plot_bgcolor',
            field=models.CharField(blank=True, default='#ffffff', max_length=30),
        ),
        migrations.CreateModel(
            name='StoreProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sp', models.CharField(blank=True, max_length=500)),
                ('var_categ', models.CharField(max_length=2000)),
                ('var_numerico', models.CharField(max_length=2000)),
                ('create_sp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_sp', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.tipodashboard')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_grafico', models.CharField(blank=True, max_length=200)),
                ('var_categorica', models.CharField(blank=True, max_length=200)),
                ('create_grafico', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_grafico', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.tipodashboard')),
                ('tipo_grafico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.tipografico')),
            ],
        ),
    ]
