# Generated by Django 3.2.15 on 2024-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20240207_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='configgrafico',
            name='var_numerico',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configgrafico',
            name='var_categorica',
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
