# Generated by Django 3.2.15 on 2023-09-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230713_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ruc_empresa',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Mantenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_publica', models.CharField(max_length=255, null=True)),
                ('api_local', models.CharField(max_length=255, null=True)),
                ('servidor_bd', models.CharField(max_length=255, null=True)),
                ('puerto_bd', models.CharField(default='1433', max_length=255, null=True)),
                ('usuario_bd', models.CharField(max_length=255, null=True)),
                ('password_bd', models.CharField(max_length=100, null=True)),
                ('name_bd', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('create_mantenedor', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_mantenedor', models.DateTimeField(auto_now=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
            ],
        ),
    ]
