# Generated by Django 3.2.15 on 2023-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_empresa_name_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenedor',
            name='name_bd',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
