# Generated by Django 3.2.15 on 2024-02-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_configdashboard_name_config'),
        ('users', '0005_alter_mantenedor_name_bd'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='config_dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.configdashboard'),
        ),
    ]
