# Generated by Django 3.2.15 on 2024-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_empresa_config_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='datos_picture',
            field=models.TextField(blank=True),
        ),
    ]
