# Generated by Django 3.2.15 on 2024-03-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='picture_empresa',
            field=models.BinaryField(null=True),
        ),
    ]
