# Generated by Django 3.2.15 on 2024-03-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_empresa_picture_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='marca_empresa',
            field=models.TextField(blank=True),
        ),
    ]
