# Generated by Django 3.2.15 on 2024-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_mantenedor_name_bd'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='api_local',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='api_publica',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='name_bd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='password_bd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='puerto_bd',
            field=models.CharField(default='1433', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='servidor_bd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_bd',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
